version: '{build}'

image: Ubuntu

stack: node 10

install:
- sh: npm install

test_script:
- sh: npm test

after_test:
- sh: npm run lint


build: off

for:
- 

  branches:
    only:
    - master
  configuration: Release
  
  environment:
    DOCKER_IMAGE: "speckle/speckleserver"
    DOCKER_USERNAME: "botsalot"
    GH_TOKEN:
      secure: 3Dr6N3HXAs/QfKZQddw+4erxGBGPA/CqrB6HQL79qz8Hdw2M27eRCRDlqsPoQtOS
    DOCKER_PASSWORD:
      secure: USQ0X2x5R969IwDYkAUvfA==

  before_deploy:
  - sh: git config --global user.email "devops@speckle.works"
  - sh: git config --global user.name "botsalot"
  deploy_script:
  - sh: npx semantic-release
